import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: Robotic Nervous System (ROS 2)',
      link: {
        type: 'doc',
        id: 'module-1/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-1'},
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo & Unity)',
      link: {
        type: 'doc',
        id: 'module-2/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-2'},
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac',
      link: {
        type: 'doc',
        id: 'module-3/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-3'},
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      link: {
        type: 'doc',
        id: 'module-4/index',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-4'},
      ],
    },
  ],
};

export default sidebars;
