# Controller Configuration for Simple Robot
# Use with ros2_control and gz_ros2_control

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Joint State Broadcaster - publishes joint states to /joint_states
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Joint Trajectory Controller - accepts trajectory commands
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Joint Trajectory Controller Configuration
joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - elbow_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0  # Hz
    action_monitor_rate: 20.0  # Hz

    allow_partial_joints_goal: false
    open_loop_control: false

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0  # 0 = no timeout

      shoulder_joint:
        trajectory: 0.1
        goal: 0.05

      elbow_joint:
        trajectory: 0.1
        goal: 0.05

# Alternative: Position Controller for individual joints
# position_controller:
#   ros__parameters:
#     joints:
#       - shoulder_joint
#       - elbow_joint
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
